using ClipYT.Interfaces;

namespace ClipYT.Services
{
    public class HolidayService : IHolidayService
    {
        private readonly Dictionary<(int Month, int Day), string> _holidays = new()
        {
            { (1, 1), "New Year's hangover" },
            { (1, 2), "National Introvert Day" },
            { (1, 4), "National Spaghetti Day" },
            { (1, 17), "International Pizza Day" },
            { (1, 18), "Blue Monday :(" },
            { (1, 19), "National Popcorn Day" },
            { (1, 28), "International LEGO Day" },
            { (2, 5), "World Nutella Day" },
            { (2, 14), "Valentine's Day" },
            { (2, 25), "Krzysztof Ibisz's Birthday" },
            { (2, 26), "Dzień Kabanosa" },
            { (3, 2), "Daniel Craig's Birthday" },
            { (3, 8), "International Women's Day" },
            { (3, 9), "National Barbie Day" },
            { (3, 13), "Marcin Najman's Birthday" },
            { (3, 14), "π Day" },
            { (3, 16), "National Panda Day" },
            { (3, 17), "St. Patrick's Day" },
            { (3, 20), "Dzień Wróbla" },
            { (3, 21), "Dzień Wagarowicza" },
            { (4, 1), "International Bird Day" },
            { (4, 4), "World Rat Day" },
            { (4, 7), "Bober Day" },
            { (4, 13), "Dzień Pamięci Ofiar Zbrodni Katyńskiej" },
            { (4, 19), "National Garlic Day" },
            { (4, 22), "Earth Day" },
            { (4, 30), "Beating Children Day" },
            { (5, 1), "Kaszanka Day" },
            { (5, 4), "International Firefighters Day" },
            { (5, 20), "World Bee Day" },
            { (5, 25), "World Football Day" },
            { (5, 26), "Mother's Day" },
            { (5, 31), "Bocian Day" },
            { (6, 1), "Children's Day" },
            { (6, 3), "World Bicycle Day" },
            { (6, 11), "Ryś Day" },
            { (6, 14), "Usual Day" },
            { (6, 15), "World Wind Day" },
            { (6, 18), "International Sushi Day" },
            { (7, 2), "World UFO Day" },
            { (7, 4), "National Hot Dog Day" },
            { (7, 7), "World Chocolate Day" },
            { (7, 24), "Święto Policji" },
            { (7, 25), "Testoviron's Birthday" },
            { (7, 29), "International Tiger Day" },
            { (7, 30), "International Sernik Day" },
            { (8, 2), "Światowy Dzień Pamięci o Zagładzie Romów" },
            { (8, 10), "World Lion Day" },
            { (8, 20), "World Mosquito Day" },
            { (8, 24), "Hideo Kojima's Birthday" },
            { (8, 26), "International Dog Day" },
            { (9, 1), "Święto Wojsk Obrony Przeciwlotniczej" },
            { (9, 15), "Dzień Majonezu Kieleckiego" },
            { (9, 22), "World Car Free Day" },
            { (9, 30), "Dzień Chłopaka" },
            { (10, 6), "Borsuk Day" },
            { (10, 8), "World Octopus Day" },
            { (10, 9), "Światowy Dzień Poczty i Znaczka Pocztowego" },
            { (10, 18), "Dzień Poczty Polskiej" },
            { (10, 31), "Halloween" },
            { (11, 1), "All Saints' Day" },
            { (11, 2), "All Souls' Day" },
            { (11, 6), "Międzynarodowy Dzień Zapobiegania Wyzyskowi Środowiska Naturalnego podczas Wojen i Konfliktów Zbrojnych" },
            { (11, 10), "Jeż Day" },
            { (11, 11), "Independence Day" },
            { (11, 18), "Mickey Mouse Day" },
            { (11, 19), "International Men's Day" },
            { (11, 23), "Fibonacci Day" },
            { (11, 25), "Dzień Tramwajarza" },
            { (12, 5), "International Ninja Day" },
            { (12, 14), "World Monkey Day" },
            { (12, 17), "Dzień bez słowa na K" },
            { (12, 24), "Christmas Eve" },
            { (12, 25), "Christmas Day" },
            { (12, 26), "Boxing Day" },
            { (12, 31), "New Year's Eve" },
        };

        public string? GetTodaysHolidayName()
            => _holidays.TryGetValue((DateTime.Now.Month, DateTime.Now.Day), out var holidayName) ? $"Happy {holidayName}!" : null;
    }
}
