name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract git version
      id: vars
      run: |
        # Get the current git tag, or fallback to commit SHA if no tag exists
        VERSION=$(git describe --tags --always --dirty)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=VERSION::$VERSION"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src/ClipYT
        platforms: linux/arm64
        push: true
        tags: |
          pawelptak/clipyt:${{ env.VERSION }}
          pawelptak/clipyt:latest
