name: Build and Push Docker Image

on:
  push:
    branches:
      - add-deploy-to-dockerhub-workflow  # TODO: replace with 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        push: true
        tags: user/app:latest
